name: barotropic_env
#channels:
#  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - coolprop
    - openpyxl
    - parse
    - black
    - ipython
    - pexpect
    - cycler
    - sphinx
    - sphinx-book-theme
    - sphinx-rtd-theme
    - pydata-sphinx-theme
    - numpydoc